const ETAPPEN = [{
        "nr": "Etappennummer",
        "titel": "Titel",
        "text": "Kurztext",
        "info": "Streckenbeschreibung",
        "start": "Ausgangspunkt",
        "ziel": "Endpunkt",
        "auf": "Höhenmeter bergauf",
        "ab": "Höhenmeter bergab",
        "hp": "Höchster Punkt",
        "grad": "Schwierigkeitsgrad",
        "km": "Streckenlänge (in km)",
        "stunden": "Gehzeit (in Stunden)",
        "einkehr": "Einkehrmöglichkeiten",
        "track": "ID in GPS-Track"
    },
    {
        "nr": "1",
        "titel": "Adlerweg-Etappe 1: St. Johann  Gaudeamushütte",
        "text": "Die erste Etappe am Adlerweg führt vom St. Johanner Ortsteil Hinterkaiser zur Gaudeamushütte auf 1.263 Metern Seehöhe. Zei besondere Naturschauspiele entlang der Strecke sind der imposante Schleierwasserfall und die Höhle Diebsöfen.",
        "info": "Start im Ortszentrum von St. Johann in Tirol beim Tourismusbüro (ca. 250 Meter von Bahnhof entfernt). Wer mit dem Auto anreist hat die Möglichkeit auf dem öffentlichen Parkplatz (kostenlos) bei Koasastadion zu parken (ca. 400 Meter vom Tourismusbüro entfernt). Vom Tourismusbüro ausgehend geht man geradeaus Richtung Kreisverkehr zur Hauptstraße, dort biegt man bei der großen Hinweistafel Hinterkaiser ab und geht auf dem Hinterkaiserweg weiter in Richtung Rummlerhof. Vom Rummlerhof (Bauernhof mit angeschlossenem Wirtshaus) im St. Johanner Ortsteil Hinterkaiser auf schmalem, asphaltierten Fahrweg nach Westen Richtung Haus Maurerhof. Bald darauf der Beschilderung Schleierwasserfall folgen. Links am (Bauern-)Haus Nr. 80 vorbei (Wasserfall, Nr.33). Nun auf Weg bzw. Steig in den Wald und mäßig steil aufwärts. Es wird eine Forststraße überquert, jenseits der Forststraße dem Steig mit der rot-weißen Markierung folgen und den Bach entlang nach oben. Der Steig mündet in einen Forstweg  hier links und wenig später wieder rechts Richtung Schleierwasserfall halten (bis zum Schleierwasserfall stets auf dem Weg Nr. 33 bleiben). Weiter durch den Wald und über den Steig (eine seilversicherte Stelle) nach Diebsöfen. Hier rinnt ein Bach unter einer Felswand vorbei, in der sich eine Höhle befindet. Hinunter ins Bachbett und den Markierungen in der Höhle folgen (Steig führt durch die Höhle durch). Von Diebsöfen auf dem Steig hinüber bzw. gemütlich nach oben zum Schleierwasser-fall (Zwickstelle Wasserfall): Hier geht man zwischen Wasserfall und Felswand. Von hier auf dem Steig Richtung Obere Regalm und ansteigend an Kletterwänden vorbei. Später vorbei an einem weiteren Wasserfall und über eine Wiese hinunter zu einer Steiggabelung  jetzt rechter Hand wieder nach oben (Nr. 817). Anschließend an Regalm bzw. Gaudeamushütte orientieren. Der Steig verläuft in dem Bereich im freien Almgebiet, in Folge erneut abwärts und später als Fahrweg hinüber zur Oberen Regalm (Zwickstelle Regalm). Oberhalb der Hütte Richtung Gaudeamushütte und auf dem Steig im freien Gelände zügig empor auf ein Joch (unmittelbar daneben Bergsteigergrab am Brennenden Palven). Jenseits des Sattels hinunter Richtung Gaudeamushütte. Der Steig leitet später unmittelbar vorbei an der Freiberghütte und recht zügig hinab zur Gaudeamushütte (Weg Nr. 35 ab dem Sattel).",
        "start": "Rummlerhof",
        "ziel": "Gaudeamushütte",
        "auf": "1060",
        "ab": "470",
        "hp": "1572",
        "grad": "mittelschwierig",
        "km": "9",
        "stunden": "5,5",
        "einkehr": "Rummlerhof#Obere Regalm#Gaudeamushütte",
        "track": "A01"
    },
    {
        "nr": "2",
        "titel": "Adlerweg-Etappe 2: Gaudeamushütte  Hintersteiner See",
        "text": "Diese Etappe führt ausgehend von der Gaudeamushütte über den Klammlweg zu einem besonderem Ziel entlang des Adlerwegs: dem Hintersteiner See. Der Bergsee lockt vor allem im Hochsommer mit Badefreuden.",
        "info": "Von der Gaudeamushütte überwindet man über den Klammlweg fast 400 Höhenmeter bis zur Gruttenhütte, der höchstgelegenen Hütte im Kaisergebiet. Dazu hält man sich zuerst in Richtung Ellmauer Tor und biegt dann Richtung Westen auf den Steig Nr. 824, 813. Der Weg führt durch Wiesen und Latschen, nach der Querung eines trockenen Bachbettes gelangt man zum Wegweiser Gruttenhütte über Klamml (Schwindelfreiheit und Trittsicherheit erforderlich). Der Weg verläuft über Steine und kleine Felsbrocken am Rand eines Gerölltrichters. Die Gaudeamushütte liegt jetzt schon deutlich unterhalb. Bald führt der schmale Weg um einen Felsen herum und man steht vor einer ca. zwei Meter langen Eisenleiter. Diese klettert man hinauf, dann geht es an einer Eisenkette entlang über einige Stufen. Links unten das Geröll, rechts die hohen Felsen, führt der Weg nun leicht bergan. Nach der Querung eines Geröllfeldes sieht man bald die Holzstufen zum Klamml-Eingang. Rechts von der Wand des Gruttenkopfs geht es steil nach oben. Der Weg ist mit Eisenklammern für Tritte und Griffe gesichert. Bei der letzten Stufe zieht man sich über einen Felsen hoch. Am Ausstieg des Klamml links halten. Neben dem schmalen Weg fällt das Gelände rechts steil ab, aber wenige Kehren später erreicht man die Kuppe, von wo ein fast ebener Weg noch ein kurzes Stück zur Gruttenhütte führt. Gleich darauf mündet von rechts der Weg vom Jubiläumssteig ein. Von der Gruttenhütte (1.620 Meter) nimmt man den Gruttenweg 14 a Richtung Südwesten.  Auf rund 1.400 Meter Höhe zweigt vom Gruttenweg im Bereich vom Krummbachegg der Höhenweg Nr. 823 Richtung Westen ab (Hintersteiner See). Jetzt auf dem Höhenweg, der auch Wilder-Kaiser-Steig genannt wird, im lichten Mischwald sowie durch Latschen und Kare südlich am Treffauer vorbei und um ihn herum marschieren, anschließend weiter Richtung Kaiser Hochalm (unbewirtschaftet). Diese liegt auf 1.417 Meter im freien Gelände, von hier aus geht es auf markiertem Weg hinunter. Nun an der Beschilderung Steiner Hochalm orientieren und dem Steig Nr. 823 folgen, der Steig verläuft durch Mischwald bergab. Am Waldrand gabelt sich die Route, an dieser Stelle rechts nach oben und dann gleich dem markierten Steig folgen, der links den Hang entlang zieht. Er führt zur Steiner Hochalm, wo man sich mit Getränken erfrischen und musikalisch erfreuen kann, denn hier gibt es oft Harfenspiel und Gesang. Südöstlich vom  Almgebäude geht es über einen Karrenweg hinab zum Hintersteiner See. Bald öffnet sich der Blick auf dieses schöne Naturjuwel. Später weiter auf einem Forstweg und dabei immer abwärts halten. Beim Gasthof Bärnstatt bzw. bei der Bärnstatt- Kapelle mündet der Weg in die Fahrstraße zum Hintersteiner See, hier geht es entlang der Straße rechter Hand weiter an Blumenwiesen und Häusern vorbei zum Ostufer des Sees. Auf dieser Etappe gibt es außer auf der Gaudeamus- bzw. Gruttenhütte zu Etappenbeginn und gegen Etappenende (Bärnstatt und am Hintersteiner See) keine Einkehrmöglichkeit mit Mahlzeiten.",
        "start": "Gaudeamushütte",
        "ziel": "Hintersteiner See",
        "auf": "800",
        "ab": "1130",
        "hp": "1630",
        "grad": "mittelschwierig",
        "km": "14,5",
        "stunden": "6",
        "einkehr": "Gaudeamushütte#Gruttenhütte#Seestüberl#Pension Maier",
        "track": "A02"
    },
    {
        "nr": "3",
        "titel": "Adlerweg-Etappe 3: Hintersteiner See  Kufstein",
        "text": "Die dritte Etappe am Adlerweg führt vom Hintersteiner See ins Städtchen Kufstein. Vom 1.470 Meter hohen Hochegg führt die sanfte Wanderung abwärts in Richtung Kufstein, wo man die imposante Festung Kufstein besichtigen kann.",
        "info": "Am Parkplatz vor dem Eingang zum Strandbad den Seeweg (Nr. 822) nehmen und entlang des Südufers bis zum  Biobauernhof Pension Maier wandern. Rechts am Bauernhof vorbei und beim Parkplatz Richtung Norden, wo der breite Wanderweg (ein privater Almzufahrtsweg) beginnt, der zur Walleralm führt. Auf diesem Weg (Nr. 45) bleibt man bis zur Walleralm, wobei man hauptsächlich in nördlicher Richtung u. a. links am Schafberg vorbei zuerst durch den Wald und später durch freies Gelände wandert, bis man schließlich ins Almgebiet gelangt. Auf der Walleralm mit dem Alpengasthaus Walleralm kann man einen beschaulichen Zwischenstopp einlegen. Dahinter beginnt der beschilderte Steig zur Kaindlhütte. Auf dem Steig großteils im bewaldeten Gebiet gemütlich empor zum Hochegg (1.470 Meter). Kurz vor dem Hochegg-Buckel nimmt die Steigung noch einmal deutlich zu. Auf der grasigen Kuppe, beim Gipfelkreuz des Hochegg, lohnt sich eine Pause mit Blick auf das Inntal und den Zahmen Kaiser. Nun geht es sanft weiter durch freie Flächen hinunter ins Almdorf der Steinbergalm mit der Kaindlhütte. Von der Hütte dem Forstweg hinunter folgen, der zunächst durch Almgebiet führt und in einem Bogen um die (geschlossene) Steinberghütte leitet. Die Forststraße legt einen kleinen Gegenanstieg zum Brentenjoch ein, wo linker Hand der ausgeschilderte, markierte Weg zum Lift abzweigt. Nun noch ein paar weitere Meter hinauf zur Liftstation. Mit der Sesselbahn Wilder Kaiser schwebt man anschließend bequem und aussichtsreich über zwei Sektionen hinunter in den Kufsteiner Ortsteil Sparchen. Variante: Zu Fuß besteht die Möglichkeit, über Aschenbrenner am Panoramaweg nach Kufstein zu gelangen.",
        "start": "Hintersteiner See",
        "ziel": "Kufstein",
        "auf": "730",
        "ab": "460",
        "hp": "1463",
        "grad": "mittelschwierig",
        "km": "9,5",
        "stunden": "3,5",
        "einkehr": "Seestüberl#Pension Maier#Stöfflhütte#Walleralm#Kaindlhütte#Gasthof Weinbergerhaus",
        "track": "A03"
    },
    {
        "nr": "4",
        "titel": "Adlerweg-Etappe 4: Kufstein   Alpengasthof Buchacker",
        "text": "Nicht ganz ohne Schweiß sind die mehr als 1.300 Höhenmeter dieser Adlerweg-Etappe zu bewältigen. Aber es lohnt sich! Am Ende der Strecke wartet ein besonderes Naturschauspiel: die Hundsalm-Eishöhle, eine auf knapp 1.400 Meter liegende Eis- und Tropfsteinhöhle.",
        "info": "In Unterlangkampfen angelangt, rechts abbiegen, durch die Unterführung, dem Weg folgend bis ins Dorf zur Kirche. Oberhalb der Kirche der Hinweistafel Höhlensteinhaus folgen. Zunächst auf dem Forstweg Richtung Höhlensteinhaus. Bald rechts auf einen Karrenweg abzweigen. Die Route verläuft in der Folge recht steil auf einem Steig durch den Wald. Der Steig führt knapp vor dem Ziel auf eine freie Almwiese, wo sich in einer Senke das Höhlensteinhaus befindet. Unmittelbar beim Höhlensteinhaus führt ein Steig weiter Richtung Köglhörndl (1.645 Meter). Die Route verläuft nun auf seinem sehr urtümlichen und steilen Steig durch den Wald in romantischer und einsamer Gegend nach oben auf den Kamm und über den Kamm bis zum Köglhörndl (1.645 Meter) mit dem Kreuz. Der Steig leitet dann wieder in den Wald hinunter. Die Route verläuft in Folge ab- und ansteigend und wieder nach oben zum Hundsalmjoch (1.637 Meter) mit dem modernen Hundsalmkreuz. Jetzt wird der Kamm verlassen, die Route führt direkt gegenüber vom Hundsalmkreuz auf markiertem Steig hinunter ins Almgelände. Durch Wiesen geht es dann auf einer Abkürzung linker Hand hinüber zum Forstweg, über den der Schlussabstieg zum Alpengasthaus Buchacker erfolgt. Kurz vorher zweigt rechter Hand der Weg zur Hundsalm Eishöhle ab (20 Minuten)",
        "start": "Kufstein",
        "ziel": "Alpengasthaus Buchacker",
        "auf": "1330",
        "ab": "500",
        "hp": "1617",
        "grad": "mittelschwierig",
        "km": "11",
        "stunden": "5,5",
        "einkehr": "Höhlensteinhaus#Gasthof Buchhacker",
        "track": "A04"
    },
    {
        "nr": "5",
        "titel": "Adlerweg-Etappe 5: Alpengasthof Buchacker  Kaiserhaus",
        "text": "Moderate Ansprüche an die Kondition stellt diese Adlerweg-Etappe, die vom Alpengasthaus Buchacker zum Gasthof Gwerchtwirt führt. Entlang der Strecke gibt es immer wieder wunderbare Ausblicke zum Kaisergebirge, zu den Kitzbühler Alpen, zum Rofangebirge, zu den Zillertaler und Stubaier Alpen, und bei guter Sicht sogar bis zum Großglockner und Großvenediger.",
        "info": "Vom Gasthof Buchacker ein Stück den Forstweg bergab bis zur nächsten Kreuzung, hier rechts dem Wegverlauf folgen bis ins Hasatal\". Dann weiter zur nächsten Kreuzung, hier links etwas ansteigend und dann bald rechts auf den Steig in Richtung Nachbergalmen\" abzweigen. Nun geht es etwas steiler bergauf bis zum Nachberg Hochleger und weiter über das Almgebiet bis zum Ascherjoch\" auf 1.458 Meter. Jetzt kommt der technisch anspruchsvollere Teil der Tour  der Weg hinauf zum Plessenberg\", ein schwarzer Bergweg mit vier Seilpassagen. Teilweise steigt man dabei recht steil aufwärts über Steintreppen und seilversicherte Stellen bis zum Gipfel auf 1.743 Meter. Von hier aus genießt man eine herrliche Aussicht zum Kaisergebirge, zu den Kitzbühler Alpen, zum Rofangebirge, zu den Zillertaler und Stubaier Alpen, bei guter Sicht sieht man sogar bis zum Großglockner und Großvenediger. Nach der verdienten Rast geht es kurz abwärts bis zum Heubergsattel, hier rechts in Richtung Kienberg halten. Der nachfolgende Aufstieg führt durch Latschenfelder zum Gipfel vom Kienberg und damit zur höchsten Erhebung der Tour auf 1.786 Meter. Damit ist das Aufstiegspensum erfüllt. Ab jetzt geht es nur noch abwärts über schöne Almgebiete, man passiert u.a. die Einkehralm und die Heubrandalm. Der Endspurt erfolgt über einen steilen Steig von Prama\" hinunter nach Pinegg, wo man sich nach dieser langen und fordernden Etappe im Gasthaus Gwercherwirt ausruhen kann, das inmitten unberührter Natur im Hochtal Brandenberg liegt.",
        "start": "Alpengasthaus Buchacker",
        "ziel": "Gasthof Gwercherwirt",
        "auf": "980",
        "ab": "1630",
        "hp": "1772",
        "grad": "leicht",
        "km": "18",
        "stunden": "3",
        "einkehr": "Gasthof Buchhacker#Gwercherwirt",
        "track": "A05"
    },
    {
        "nr": "6",
        "titel": "Adlerweg-Etappe 6: Kaiserhaus  Steinberg am Rofan",
        "text": "Gemütlich und dennoch lohnend ist die leichte Wanderung auf dieser Adlerweg-Etappe vom Gasthof Gwerchtwirt zum Gasthof Waldhäusl in Steinberg am Rofan. ",
        "info": "Von Pinegg geht es über zwei Brücken  der Brandenberger Ache und danach der Steinberger Ache  zum ersten Anstieg dieser Etappe. Er verläuft vorerst über einen Wanderweg, dann über die Forststraße zum Jägersteig der nach Aschau, einem Ortsteil von Brandenberg, führt. Man durchwandert das kleine Dorfzentrum auf der Hauptstraße bis kurz vor dem Gasthaus Haaser. Von hier aus geht es den Burgstallgraben hinauf bis zum letzten Bauernhof Wimm\". Nach dem Weiderost rechts und weiter der Beschilderung folgen bis zum Wimmerjoch. Hier, am höchsten Punkt der Etappe, lohnt es sich, auf den grünen Almwiesen eine kleine Pause einzulegen. Anschließend links halten und abwärts in Richtung Lahnalm wandern. Kurz vor der Alm der Beschilderung zum Weißenbachgraben folgen. Sobald man den Weißenbach, den Grenzbach zwischen Brandenberg und Steinberg, überquert hat, ist es nur noch ein kurzer Weg zum Enterhof, einem stattlichen Bauernhaus mit Übernachtungsmöglichkeit. Diesen lässt man links liegen und folgt der Straße hinunter ins Steinberger Loch, wobei man zum zweiten Mal auf dieser Etappe die Steinberger Ache überquert. Danach bei der ersten Möglichkeit rechts auf den Hinterbergweg einbiegen. Diesem in Richtung Norden bis nach Vordersteinberg folgen, die Straße überqueren und weiterwandern zum Bärenwaldweg. Nun nur noch diesem Weg folgen und den Ausklang des Wandertages in der idyllisch gelegenen Jausenstation Gasthof Waldhäusl am westlichen Ortsrand von Steinberg genießen. Eine bequeme Übernachtungsmöglichkeit gibt es hier auch.",
        "start": "Gasthof Gwercherwirt",
        "ziel": "Gasthof Waldhäusl",
        "auf": "1100",
        "ab": "780",
        "hp": "1327",
        "grad": "leicht",
        "km": "18",
        "stunden": "3,5",
        "einkehr": "Gwercherwirt#Gasthof Waldhäusl",
        "track": "A06"
    },
    {
        "nr": "7",
        "titel": "Adlerweg-Etappe 7: Steinberg am Rofan  Erfurter Hütte",
        "text": "Von Steinberg am Rofan führt diese anspruchsvolle Adlerweg-Etappe über fast 1.600 Höhenmeter zur Erfurter Hütte. Die Route entlang des Rofangebirges ist landschaftlich äußerst reizvoll: Auf der einen Seite haben die Berge steile Felswände, auf der anderen sind sie mit sanften Almmatten gepolstert.",
        "info": "Vom Gasthof Waldhäusl ein paar Meter nach Südosten und dann gleich die Dorfstraße nehmen, die links von der Hauptstraße abzweigt. Nach einem kurzen Stück rechts abbiegen Richtung Durrahof. Auf der weitgehend verkehrsfreien Fahrstraße gemütlich hinunter ins kleine Tal des Mühlbachs, den Bach entlang und in der Folge über die Ache. Dann wieder gemütlich nach oben vorbei am Enterhof bis zum Durrahof. Ab hier orientiert man sich an der Beschilderung Rofan und wandert auf einem Forstweg weiter. Später folgt man der Beschilderung Zireiner See bzw. Erfurter Hütte, die Strecke verläuft kaum spürbar ansteigend durch lichten Wald und Wiesen. Nach einem Hof teilt sich der Weg  hier die obere Route nehmen und nicht hinunter gehen. Der Weg verwandelt sich gleich in einen Steig. Nach der Überquerung eines Bachs mit einem kleinen Wasserfall trifft der Steig auf einen Fahrweg  hier rechts auf dem Fahrweg Richtung Bayreuther Hütte. Bei der folgenden Weggabelung links hinauf und den Bach entlang nach oben. Später über einen Steig zu einer breiten Forststraße. Rechts weiter und gleich anschließend linker Hand den Fahrweg hinauf nehmen, der rasch zum Steig wird. Auf dem Steig im lichten Wald den Bach entlang Richtung Zireiner See. Der Bach wird überquert (keine Brücke), es geht nun steiler im Wald hinauf ins freie Almgelände zur idyllische Schauertalalm. Anschließend auf dem Steig nach oben Richtung Schauertalsattel. Der nun recht steinige, mit Wurzeln überwachsene Steig verläuft in dem Abschnitt direkt und zügig empor, vielfach durch Latschen. Man gelangt in einen Kessel  hier Richtung Erfurter Hütte und südlich am Zireiner See vorbei. Nun an Marchalm orientieren, wenig später Richtung Schafsteig (Achtung bei Nässe!), Rofan. Der Schafsteig zieht die Rofanspitz-Ostwand entlang und dann schräg nach oben, ehe er durch steiles Gelände zum Schafsteigsattel nordöstlich der Rofanspitze leitet. Vom Sattel linker Hand im sanften Wiesengelände ein kurzes Stück abwärts. Wenig später der Beschilderung Erfurter Hütte bzw. Rofanseilbahn folgen und auf dem Steig südlich der Rofanspitze beinahe eben hinüber zum Joch. Der Steig leitet anschließend sanft hinab in ein grünes Becken. Von hier weiter gemütlich im Almgelände hinunter zur Erfurter Hütte direkt neben der Bergstation der Rofanseilbahn. Kurz vor dem Ziel führt die Route noch an der Mauritzalm vorbei. Ab dem Schafsteigsattel folgt man stets der Beschilderung Erfurter Hütte bzw. Rofanseilbahn. Von dort entweder zu Fuß (ca. 1 ½ Std.) oder mit der Seilbahn nach Maurach. Nahezu die gesamte Strecke verläuft entlang des Nordalpenwegs 01.",
        "start": "Gasthof Waldhäusl",
        "ziel": "Erfurter Hütte",
        "auf": "1590",
        "ab": "770",
        "hp": "2192",
        "grad": "schwierig",
        "km": "18",
        "stunden": "7",
        "einkehr": "Gasthof Waldhäusl#Erfurter Hütte#Berggasthof Rofan#Mauritzalm",
        "track": "A07"
    },
    {
        "nr": "8",
        "titel": "Adlerweg-Etappe 8: Erfurter Hütte  Lamsenjochhütte",
        "text": "Diese Etappe am Adlerweg beginnt entweder mit einer Seilbahnfahrt von der Erfurter Hütte hinunter nach Maurach oder startet direkt in Maurach. Weiter führt die Route am Achensee entlang nach Pertisau und ins sanft ansteigende Falzthurntal bis zur Gramaialm.",
        "info": "Von der Erfurter Hütte mit der Rofanseilbahn hinunter nach Maurach oder startet bereits in Maurach. Von dort auf dem Fußweg das Süd- bzw. Südwestufer des Achensees entlang nach Pertisau zum Beginn der Mautstraße in die Karwendeltäler (in Pertisau an den Schildern Karwendeltäler orientieren). Unmittelbar nach der Mautstelle links der Beschilderung Gramaialm ins Falzthurntal folgen. Jetzt auf einem breiten, asphaltierten Fußweg im Wald kaum spürbar ansteigend zur Falzthurnalm mit der Sennhütte Falzthurn und dem Alpengasthof Falzthurn. Hier endet der asphaltierte Abschnitt. Anschließend auf einem sanft ansteigenden Fußweg über Wiesen weiter ins Tal hinein (nirgendwo links den Hang hinauf), hie und da das in der Regel ausgetrocknete Schotterbachbett überquerend, bis zur Gramaialm. Von der Gramaialm zunächst auf dem Fahr- bzw. Karrenweg weiter taleinwärts Richtung Lamsenjochhütte. Bald wird das meist ausgetrocknete Bachbett nach links überquert. Die Route zieht durch den Talboden und vorbei an der Abzweigung zum Gramai-Hochleger. Ab hier verläuft die Etappe auf einem Steig. Es geht durch den Gramaier Grund und auf den steilen Hang im Talschluss (Süden) zu, über dem rechts markant die Lamsenspitze aufragt. Der Steig leitet in der Folge ein kurzes Stück links den Hang empor, um anschließend taleinwärts Schuttreisen zu queren. Zum Schluss schraubt sich die Route in Serpentinen den zum Teil schottrigen und recht steilen Hang nach oben. Schließlich vom Joch in wenigen Schritten links hinüber zu der bereits sichtbaren Lamsenjochhütte.",
        "start": "Erfurter Hütte",
        "ziel": "Lamsenjochhütte",
        "auf": "1030",
        "ab": "70",
        "hp": "1949",
        "grad": "mittelschwierig",
        "km": "17",
        "stunden": "2",
        "einkehr": "Erfurter Hütte#Berggasthof Rofan#Mauritzalm#Falzthurnalm#Sennhütte #Gramaialm#Lamsenjochhütte",
        "track": "A08"
    },
    {
        "nr": "9",
        "titel": "Adlerweg-Etappe 9: Lamsenjochhütte  Falkenhütte",
        "text": "Diese Etappe am Adlerweg führt von der 1908 errichteten Lamsenjochhütte auf knapp 2.000 Metern zur Falkenhütte. Die Tour durchquert dabei den Großen Ahornboden, ein Naturdenkmal mit mehr als 2.000 Bergahornen.",
        "info": "Von der Lamsenjochhütte auf dem Steig ein paar Meter entlang der Aufstiegsroute zurück, auf der Einsattelung jedoch Richtung Binsalm bzw. Falkenhütte. Der Steig leitet im abschüssigen Gelände unter der Lamsenspitze hindurch sanft absteigend zum Westlichen Lamsenjoch (1.940 Meter). Auf der anderen Seite des Jochs auf dem Steig Richtung Binsalpe bzw. Eng absteigen. Der Steig verwandelt sich bald in einen Karren- bzw. Fahrweg. Die Route führt zunächst durch freies Gelände und vorbei am Binsalm-Hochleger. Abschnittsweise gibt es dann Abkürzungsmöglichkeiten auf einem Steig. Man gelangt zum Binsalm-Niederleger. Vom Niederleger auf einem breiten Fahrweg und einige Zeit praktisch parallel zu einem tief eingeschnittenen Tal hinunter ins Almdorf der Eng. Hinter den letzten Gebäuden in der Eng beginnt rechter Hand der breite Fußweg zur Falkenhütte. Der Weg steigt sanft an und führt durch Wiesen und Mischwald nach oben auf das Hohljoch (1.794 Meter). Vom Joch auf einem guten Steig unterhalb der Laliderer Wände hinab bis auf knapp 1.700 Meter. Dabei werden die Laliderer Reisen gequert. Der Steig zieht schließlich sanft nach oben zum Spielissjoch, die letzten Meter zur Falkenhütte werden auf einem Fahrweg zurückgelegt.",
        "start": "Lamsenjochhütte",
        "ziel": "Falkenhütte",
        "auf": "810",
        "ab": "920",
        "hp": "1959",
        "grad": "mittelschwierig",
        "km": "12,5",
        "stunden": "4,5",
        "einkehr": "Lamsenjochhütte#Binsalm#Engalm#Falkenhütte",
        "track": "A09"
    },
    {
        "nr": "10",
        "titel": "Adlerweg-Etappe 10: Falkenhütte  Karwendelhaus",
        "text": "Diese Adlerweg-Etappe startet auf der Falkenhütte und führt durch Almwiesen und einem lichten Wald sanft abwärts zum Etappenziel, dem Karwendelhaus. Dabei quert die Route den Kleinen Ahornboden, eine Weide mit mehreren Jahrhunderte alten Ahornen.",
        "info": "Nördlich unterhalb der Falkenhütte folgt man der Beschilderung Karwendelhaus und wandert auf einem guten Steig durch Almwiesen sanft abwärts. Später weiter abwärts über einen Fahr- bzw. Karrenweg. Vorbei an der Ladizalm mit dem historischen Almhaus und anschließend im (lichten) Wald hinunter (stets auf dem Karrenweg bleiben). Nach der Überquerung des meist ausgetrockneten, breiten Schotterbachbetts führt die Route zum Kleinen Ahornboden und mündet in eine breite Forststraße, die gleich zum Hermannvon- Barth-Denkmal und den alten Forsthäusern unmittelbar oberhalb des Denkmals führt. Auf der Forstraße links an den Forsthäusern vorbei aufwärts Richtung Karwendelhaus. Der Forstweg verwandelt sich im lichten Wald rasch in einen Karrenweg, später in einen Steig. Der Steig leitet in der Folge sanft durch das liebliche Untere Filztal empor, eher er später ins Almgelände zieht (insgesamt praktisch stets in gleichbleibender Richtung). Wenig später mündet der Steig in einen Fahrweg. Nun auf dem Fahrweg weiter in gleichbleibender Richtung durch die Wiesen zum Hochalmsattel mit dem Jochkreuz. Anschließend auf dem Fahrweg ein paar Meter abwärts und links hinüber zum Karwendelhaus.",
        "start": "Falkenhütte",
        "ziel": "Karwendelhaus",
        "auf": "440",
        "ab": "520",
        "hp": "1843",
        "grad": "mittelschwierig",
        "km": "9",
        "stunden": "3,25",
        "einkehr": "Falkenhütte#Karwendelhaus",
        "track": "A10"
    },
    {
        "nr": "11",
        "titel": "Adlerweg-Etappe 11: Karwendelhaus  Hallerangerhaus",
        "text": "Hinauf in höchste Höhen führt die alpinistisch anspruchsvollste Adlerweg-Etappe im Karwendel. Neben dem Karwendelhaus startet die Route und führt auf die 2.749 Meter hohe Birkkarspitze. Nach dem Gipfelsieg erfolgt der Abstieg ins schöne Hinterautal und weiter bis zum Etappenziel, dem Hallangerhaus.",
        "info": "Neben dem Karwendelhaus beginnt der markierte Steig zur Birkkarspitze. Der zieht zunächst recht steil und stellenweise seilversichert im felsdurchsetzten Gelände durch Latschen und Lawinenverbauten empor. Es geht dann in südöstlicher Richtung und nicht mehr so steil hinüber ins schier endlose Schlauchkar. Die Route leitet vorbei an der Abzweigung zum Hochalmkreuz (links) und an der Abzweigung zum Brendelsteig (rechts). Man behält hier die Richtung bei und wandert etwas mühsam  teilweise in felsdurchsetztem Gelände und vielfach in äußerst unangenehmem Geröll  durch das Kar hinauf (Steinmännchen). Der Steig gewinnt zunehmend an Steilheit, der letzte Abschnitt zum Schlauchkarsattel verläuft in südwestlicher Richtung. In dem Bereich muss in der Regel ein (meist hartes) Schneefeld überquert werden  man folgt am besten den Trittspuren. Vom Schlauchkarsattel (2.639 Meter) dann an der Birkkarhütte (Notunterstand) vorbei und über die seilversicherte Steiganlage in einfacher Kraxelei den Westgrat entlang hinüber zum Gipfel der Birkkarspitze (2.749 Meter) mit dem Kreuz. Vom Gipfel wieder zurück zum Schlauchkarsattel und im Süden hinab. Zunächst zieht die Route durch Blockwerk und stellenweise seilversichert steil abwärts ins Westliche Birkkar. Im Kar auf guten Steig weiter  vielfach durch Geröllfelder, abschnittsweise erneut recht steil. Schließlich an der orografisch linken Seite des Birkkarbachs ziemlich gerade hinunter ins Hinterautal zur Forststraße. Nun im Talboden einwärts und Richtung Kastenalm bzw Hallerangerhaus. Auf dem Fahrweg rechts an der Kastenalm bzw. am Jagdhaus Kasten vorbei und in der Folge im lichten Wald steil aufwärts (oberhalb des in dem Bereich tief eingegrabenen Lafatscherbachs). Der Fahrweg führt in eine Art Hochtal, durch das die Strecke zunächst sanft ansteigend bzw. beinahe eben neben dem Lafatscher Bach verläuft. Nach der Jagdhütte geht es erneut ein wenig steiler nach oben ins Almgebiet des Lafatscher-Niederlegers mit dem urigen steiler nach oben ins Almgebiet des Lafatscher-Niederlegers mit dem urigen Almhaus. Hier durch die Wiesen gemütlich weiter. Bei der Weggabelung rechts Richtung Hallerangerhaus halten (links: Hallerangeralm  jeweils 10 Minuten). Jetzt die letzten Höhenmeter empor zum Etappenziel.",
        "start": "Karwendelhaus",
        "ziel": "Hallerangerhaus",
        "auf": "1440",
        "ab": "1450",
        "hp": "2749",
        "grad": "schwierig",
        "km": "14",
        "stunden": "8",
        "einkehr": "Karwendelhaus#Kastenalm#Hallerangerhaus#Hallerangeralm",
        "track": "A11"
    },
    {
        "nr": "12",
        "titel": "Adlerweg-Etappe 12: Hallerangerhaus   Nordkette Innsbruck",
        "text": "Diese Etappe führt vom Hallangerhaus zum Hafelekar auf der Innsbrucker Nordkette. Der Weg dorthin führt am Zugspitzblick vorbei, wo man bei schönem Wetter einen Blick auf Deutschlands höchsten Berg erhaschen kann. Am Hafelekar wartet dann noch der einzigartige Blick auf die Landeshauptstadt.",
        "info": "Vor der Hütte zunächst auf dem Steig Richtung Lafatscher Joch. Der Steig führt in ein Schuttkar, das zunehmend steiler und schmäler wird. Die Route leitet dann bald durch den so genannten Durchschlag (hier wurde der alte Saumweg durch den Felsen gebrochen) und wenig später  vorbei an einem Kreuz  sanft hinauf auf einen Boden (in dem Bereich Abzweigemöglichkeit zur Speckkarspitze). Über den Boden geht es in nördlicher Richtung gemütlich zum Lafatscher Joch. Am Joch der Beschilderung Pfeishütte folgen. Auf dem Steig sanft hinunter und sich an Pfeishütte orientieren bzw. in Folge an Pfeishütte über Wilde-Bande-Steig. Auf dem urtümlichen Wilde-Bande-Steig vielfach durch Latschen, mehrmals Rinnen überquerend, leicht ansteigend hinüber bis zum Einstieg ins Kar unterhalb des Stempeljochs. Hier an Stempeljoch bzw. Pfeishütte orientieren. Die Steiganlage (mit Brettern gebaut, zahlreiche Drahtseile) durch das Kar wird zunehmend steiler, der (zunächst schottrige) Untergrund dafür weiter oben fester. Vom Joch rechter Hand hinunter und durch Wiesen bzw. Almgebiet gemächlich zur Pfeishütte. Direkt bei der Pfeishütte beginnt der beschilderte Goetheweg (Nr. 219). Der führt als Fußweg bzw. später als Steig gemütlich ansteigend in den Kessel südlich des Schutzhauses. Bei einer Weggabelung Richtung Mandlscharte bzw. Hafelekar Bergstation, bei der folgenden Weggabelung rechter Hand weiter (links ginge es zur Arzler Scharte) und in einer weiten Schleife durch ein Schuttkar empor zur Mandlscharte. Von der Scharte jenseits durch Geröll hinab. Der jetzt wieder gute und recht breite Steig quert nun praktisch stets auf derselben Höhe unter den Felsen die Schuttreisen (toller Blick zur Rückseite der Nordkette). Nach einem kurzen Anstieg wird auf die Inntalseite gewechselt und dort in Serpentinen ein paar Meter abgestiegen. Anschließend auf dem bequemen Steig im oberen Bereich der abschüssigen, teilweise grasbewachsenen Südflanke der Nordkette insgesamt leicht ansteigend nach Westen zur Hafelekar - Bergstation (stets der Beschilderung Hafelekar Bergstation bzw. Goetheweg folgen). Zum Schluss abwechselnd links bzw. rechts vom Grat. Der Goetheweg ist vielfach ausgezeichnet versichert. Bei der Talfahrt mit der renovierten Nordkettenbahn und der neuen Hungerburgbahn gelangt man direkt in das Stadtzentrum zum Congress Innsbruck, wobei der Abstieg auch zu Fuß möglich ist, wo als Zwischenstation eine Besichtigung des Alpenzoos eingebaut werden kann.",
        "start": "Hallangerhaus",
        "ziel": "Innsbruck",
        "auf": "1150",
        "ab": "970",
        "hp": "2280",
        "grad": "schwierig",
        "km": "13",
        "stunden": "5,5",
        "einkehr": "Hallerangerhaus#Hallerangeralm#Pfeishütte#Bergstation Hafelekar",
        "track": "A12"
    },
    {
        "nr": "13",
        "titel": "Adlerweg-Etappe 13: Innsbruck  Zirbenweg  Innsbruck",
        "text": "Diese Adlerweg-Etappe verläuft am Zirbenweg entlang durch einen der ältesten Zirbenbestände Europas. Von verschiedenen Aussichtspunkten gibt es immer wieder traumhafte Ausblicke auf Innsbruck und Hall sowie Teile des Inntals oder das Landschaftsschutzgebiet Viggartal.",
        "info": "Von Innsbruck/Hauptbahnhof mit dem Bus bzw. der Straßenbahn nach Igls/Talstation Patscherkofelbahn und mit der Seilbahn zur Bergstation Patscherkofel. Bei der Bergstation (1.964 Meter) gleich der Beschilderung  Zirbenweg (Nr. 350) folgen, der direkt oberhalb des Schutzhauses Patscherkofel auf breitem Pfad Richtung Osten führt. Hier beginnt gleichzeitig der Naturlehrpfad Patscherkofel des Alpenvereins. Der breite Pfad bzw. Steig zieht knapp oberhalb der Waldgrenze im freien, aber nicht völlig baumlosen Gelände (Zirben) insgesamt leicht ansteigend hinüber zur etwas versteckten Boscheben Hütte (2.035 Meter, hier Abzweigemöglichkeit ins Viggartal zum Meißner Haus; bis hierher führt der Naturlehrpfad entlang des Zirbenwegs). Von Boscheben in gleich bleibender Richtung weiter und nördlich unterhalb der kleinen Gipfel bleiben (nirgendwo ins Tal absteigen). Auf dem Steig hinüber zur Tulfeinalm und von dort in wenigen Minuten ein paar Meter empor zum Halsmarterlift. Der Zirbenweg verläuft nach Boscheben leicht an- und absteigend jedoch ohne wesentliche Höhenänderung entlang bzw. knapp über der 2.000-Meter-Marke  in der Regel etwas oberhalb der Waldgrenze, jedoch nicht im baumfreien Gebiet (Zirben!). Mit dem Lift nach Tulfes, von dort mit dem Bus nach Igls und von Igls mit dem Bus bzw. der (Straßen)bahn zurück nach Innsbruck. Wer wieder zu Fuß zur Talstation der Patscherkofelbahn gehen möchte, der geht von der Talstation Glungezerbahn am Speckbacherweg über Rinn und Sistrans nach Igls (Gehzeit ca. 3 Std.). Von der Talstation Patscherkofel/Igls zum Hauptbahnhof geht es von Igls nach Vill durch den Wald zur Poltenhütt; Haltestelle Tantegert, Abzweigung Richtung Bretterkeller, über Brücke Autobahn überqueren, ca. 200 Meter Richtung Westen zum Gasthof Bierstindl  Stift Wilten  Leopoldstraße  rechts zur Fußgängerunterführung Olympiabrücke  Südbahnstraße bis zum Bahnhof (Gehzeit ca. 1 ½ Std.).",
        "start": "Innsbruck Hauptbahnhof",
        "ziel": "Innsbruck Hauptbahnhof",
        "auf": "300",
        "ab": "200",
        "hp": "2060",
        "grad": "leicht",
        "km": "8",
        "stunden": "2,5",
        "einkehr": "Patscherkofelhaus#Boschebenalm#Tulfeinalm",
        "track": "A13"
    },
    {
        "nr": "14",
        "titel": "Adlerweg-Etappe 14: Innsbruck  Solsteinhaus",
        "text": "Mit der Mittenwald- oder Karwendelbahn geht es von Innsbruck nach Hochzirl und weiter nach Seefeld. Von dort führt diese Etappe zum Solsteinhaus im Karwendel.",
        "info": "Mit der Mittenwaldbahn von Innsbruck oder zu Fuß vom Bahnhof in Richtung Westen der Salurnerstraße bis zur Triumphpforte folgend  dann nach links in die Maria- Theresien-Straße bis diese immer geradeaus in die Altstadt zum Goldenen Dachl führt  dort rechts vorbei in die Domgasse bis zum Dom zu St. Jakob. Dem Jakobsweg durch Innsbruck weiter nach Kranebitten, Völs, Kematen folgend und dann ab Kematen dem Wanderweg über die Innbrücke in Richtung Zirl nehmen, um dann weiter durch die Ehnbachklamm in Richtung Plainer zum Bahnhof Hochzirl und direkt vom Bahnhof der Beschilderung Solsteinhaus folgen. Nördlich der Gleise gleich auf einem guten Steig in den dichten Wald hinein. Der Steig mündet nach kurzer Zeit in einen Karrenweg, auf diesem direkt und recht steil nach oben. Bald mündet links der Weg vom Krankenhaus Hochzirl ein, weiter aufwärts und in nordöstlicher Richtung steil durch den Wald. Nach der Überquerung des kleinen Bachs, der vom Brunnenschrofen herunterrinnt, ein kurzes Stück fast eben bzw. nur sanft ansteigend dahin. Die Route ähnelt jetzt beinahe einem Fahrweg und zieht bald wieder kräftiger empor. In einer Höhe von rund 1.350 Metern trifft die Route mit einem breiten Forstweg zusammen  hier weiter nach oben. Es geht oberhalb einer kleinen Schlucht vorbei und nach dem Bach über einen Steig im lichter werdenden Wald bzw. durch die Latschen empor ins freie Almgebiet bei der lieblichen Solnalm. Von der Solnalm erblickt man erstmals das Solsteinhaus. Rechts an der Alm vorbei und in nördlicher Richtung taleinwärts auf das Höllkar zu. Dabei wird die eine oder andere Schuttrinne überquert. Der Steig überquert dann die Ausläufer des Höllkars sowie den Bach und zieht schließlich in den Latschen gemütlich den Hang nach oben zum Erlsattel mit dem Solsteinhaus.",
        "start": "Innsbruck Hauptbahnhof",
        "ziel": "Solsteinhaus",
        "auf": "940",
        "ab": "70",
        "hp": "1805",
        "grad": "mittelschwierig",
        "km": "7",
        "stunden": "2,75",
        "einkehr": "Solsteinhaus",
        "track": "A14"
    },
    {
        "nr": "15",
        "titel": "Adlerweg-Etappe 15: Solsteinhaus  Leutasch",
        "text": "Mitten durchs Karwendel führt diese Etappe und verläuft über die Eppzirler Scharte in das Leutaschtal und weiter zu den 24 Weilern der Gemeinde Leutasch. Dabei werden Almgebiete, Mischwälder und die Gießenbachklamm durchquert.",
        "info": "Beim Solsteinhaus der Beschilderung Eppzirler Scharte bzw. Eppzirler Alm folgen. Zunächst auf markiertem Steig durch das Almgebiet der Erlalm hinauf. Der Steig leitet in der Folge durch Schutt und Felsen hinüber zum Beginn des Schuttkars, empor zur Eppzirler Scharte. Beim Anstieg durch das Kar teilt sich der Steig  hier rechter Hand Richtung Eppzirler Scharte (Nr. 212) und steil, aber auf gutem Steig zu der Scharte zwischen Kuhlochspitze und Erlspitze. Jenseits durch das oben steile und später sehr weite Schuttkar (Kuhloch) ebenfalls auf gutem Steig und teilweise in Serpentinen hinab. Bei etwa 1700 Meter taucht der Steig ein in grünes Almgebiet. Es folgt noch einmal eine kurze Steilstufe (Schutt), ehe die Route endgültig den Almboden erreicht. In der Folge sanft absteigend und schlieslich parallel zum (ausgetrockneten) Bachbett hinaus zur Eppzirler Alm. Von der Alm auf dem breiten Fahrweg im Weidegebiet gemutlich abwärts und stets durch das Eppzirler Tal in gleichbleibender Richtung auswarts. Vorbei an der Abzweigung zur Oberbrunnalm (Abzweigung bei 1.200 Meter) und weiter meist sanft absteigend Talauswarts. Der Fahrweg fuhrt jetzt den Giesenbach entlang (abwechselnd links und rechts vom Bach) und in die  zunächst noch bewaldete  Giesenbachklamm. Die Klamm wird zunehmend felsiger. Der Weg leitet schließlich zum Parkplatz für die Eppzirler Alm im Scharnitzer Ortsteil Giesenbach. Dann das Gleis und die Hauptstraße überqueren, in der Siedlung die erste Straße rechts Richtung Scharnitz nehmen, anschließend links Richtung Hoher Sattel. Spater Richtung Bogenschiesstand bzw. Scharnitz, dann links ab Richtung Leutasch und bald rechter Hand den Forstweg Leutasch über Hohen Sattel nehmen. Nach dieser kurzen ebenen Passage in Giesenbach führt der Forstweg mäßig steil hinauf und in der Folge sanft im lichten Mischwald durch die Sattelklamm empor. Ab dem Wegende zieht ein Steig im lichten Wald den Hang entlang und (im Mittelteil) recht zugig aufwärts. Der Steig mundet in einen Weg  hier in gleichbleibender Richtung weiter zum Hohen Sattel, stets der Beschilderung Leutasch/Ahrn folgend. Jenseits des Sattels auf breitem Forstweg im lichten Wald (mitunter recht steil) durch das Satteltal hinunter nach Leutasch/Ahrn zur Brücke über die Leutascher Ache (unmittelbar vor dem Ziel nichts links abzweigen).",
        "start": "Solsteinhaus",
        "ziel": "Leutasch/Ahrn",
        "auf": "870",
        "ab": "1530",
        "hp": "2110",
        "grad": "mittelschwierig",
        "km": "20",
        "stunden": "6,5",
        "einkehr": "Solsteinhaus#Eppzirleralm",
        "track": "A15"
    },
    {
        "nr": "16",
        "titel": "Adlerweg-Etappe 16: Leutasch  Ehrwald",
        "text": "Vorbei an den lieblichen Almen des Gaistals und entlang des natürlichen Bachbetts der Leutascher Ache führt diese Adlerweg-Etappe in Richtung Zugspitze.",
        "info": "Im Leutascher Ortsteil Ahrn bei der Brücke über die Leutascher Ache (Ausgangspunkt für den Hohen Sattel) an der orografisch linken Seite der Ache auf dem Fußweg Richtung Weidach. Bald wird auf die rechte Seite gewechselt (in diesem Bereich Richtung Unterweidach bzw. Achweg Weidach). Man folgt dann im Prinzip auf dem Achweg stets der Leutascher Ache an deren orografisch rechtem Ufer bis zum Kalvarienberg am Beginn des Gaistals. Hier auf einem Eisensteg die Ache überqueren, ein paar Meter taleinwärts gehen, beim Mauthäuschen gleich wieder zurück auf die rechte Bachseite wechseln und dort taleinwärts weiter. Kurz vor dem Salzbachparkplatz der Beschilderung Almenparadies Gaistal folgen und abermals die Ache überqueren. Dann jedoch nicht hinaus zum Parkplatz, sondern vorher links dem breiten Fahrweg ins Gaistal folgen. Nach wenigen Metern rechts abzweigen zum Ganghoferweg. Dieser breite Fußweg führt zunächst ein kurzes Stück steil nach oben. Wenig später sanft ansteigend im lichten Wald und entlang von Wiesen unterhalb der Hämmermoosalm vorbei stets taleinwärts (Gaistalalm, Tillfußalm). Der Weg überquert den Leitenbach und führt nun ein paar Meter hinunter zur Gaistalalm (Ende des Ganghoferwegs). Von der Einkehr geht es in gleich bleibender Richtung zunächst über Almwiesen weiter zur Tillfußalm. Der Fußweg verwandelt sich bald in einen Steig, taucht in den Wald ein und steigt geringfügig an. Schließlich kaum spürbar hinab zur Tillfußalm. Von da weiter auf dem breiten Talweg nach Westen, parallel zum Bachbett der Leutascher Ache bzw. des Gaistalbachs. Bei der Weggabelung geradeaus (Ehrwalder Alm über Igelsee). Die Route verläuft zwischen den immer markanter werdenden Mieminger Bergen links und dem Wettersteingebirge rechts. Es geht insgesamt sanft aufwärts und über eine Kuppe zum Igelsee. Hinter dem See bei der Weggabelung rechts und etwas steiler empor bis rund 1.600 Meter (hier Einmündung des Steigs von der Pestkapelle). Weiter auf der Forststraße hinunter zur Ehrwalder Alm und zur Bergstation der Ehrwalder Almbahn. Unterhalb der Ehrwalder Alm beginnt der Wiesenweg nach Ehrwald. Zunächst durchs Skigebiet, an der Weggabelung geradeaus bzw. rechts und ein Stück steil durch den Wald. Später leitet der Fußweg durch herrliche Bergmähder hinaus zur Talstation der Ehrwalder Almbahn. Entweder auf dem Zufahrtsweg oder auf dem Altmühlensteig (beginnt ein paar Meter südwestlich der Talstation auf der orografisch linken Seite des Geißbachs) hinaus nach Ehrwald.",
        "start": "Leutasch/Ahrn",
        "ziel": "Ehrwald",
        "auf": "590",
        "ab": "730",
        "hp": "1597",
        "grad": "leicht",
        "km": "23",
        "stunden": "7",
        "einkehr": "Gaistalalm#Tillfussalm#Erwalder Alm",
        "track": "A16"
    },
    {
        "nr": "17",
        "titel": "Adlerweg-Etappe 17: Ehrwald  Lorea Hütte",
        "text": "Moosweg, Blindsee, Via Claudia Augusta oder Schloss Fernstein: Von einem Landschaftsjuwel zum nächsten geht es entlang dieser Adlerweg-Etappe.",
        "info": "In Ehrwald beginnt zwischen dem Hotel Grüner Baum und dem Sparmarkt der beschilderte Moosweg nach Lermoos. Nach der Großen Moosbrücke über die Loisach dann entweder links oder rechts vom Lussbach bis zum Ortsanfang von Lermoos. Dort durch den Ort zur Talstation der Grubigsteinbahn (bis hierher kein nennenswerter Höhenunterschied). Mit dem Lift zur Grubigalm (1.720 Meter). Hinter der Talstation der neuen 6-er-Sesselbahn den Fußweg Nr. 15 nehmen (Nähe Wegkreuz) und  ein wenig auf und ab  im Wald nach oben bis auf rund 1.750 Meter. Jetzt auf dem breiten Fußweg im Wald gemütlich hinunter. Die Route taucht nun in die Latschen ein (Blick zum Blindsee, stellenweise etwas steiler hinab). Die Strecke führt weiter unten erneut in den Wald. Der Fußweg bzw. Steig mündet in einen Forstweg  an der Stelle weiter hinunter. Die Route führt zur Fernpassbunde straße. Neben der Straße etwa 5 Minuten rechts hinüber zum Fernpass. Nördlich vom Gasthof Fernpass auf der alten Römerstraße sanft hinunter (Nassereith, Via Claudia Augusta). Bei der Weggabelung rechts weiter, anschließend bald links hinunter Richtung Fernstein, Nassereith (kurz eine Art Schotterpiste). Bald am Schanzlsee vorbei (nach dem See auf der Route für Radfahrer und Fußgänger bleiben). Die alte Römerstraße (kurzer Abschnitt ein Steig) leitet gemütlich hinab zum Schloss Fernstein mit dem Hotel. Vom Schloss Fernstein auf der alten Römerstraße leicht bergab weiter. Nach wenigen Metern zweigt rechts der Steig zur Loreahütte in den Wald ab. Auf dem Steig sehr steil und vielfach in Serpentinen neben dem Bach durch den Wald empor. Der Steig führt später durch Latschenbestände und zum Schluss über weite Almböden  jetzt weniger steil  zur Loreahütte.",
        "start": "Ehrwald",
        "ziel": "Lorea Hütte",
        "auf": "1170",
        "ab": "1190",
        "hp": "2022",
        "grad": "mittelschwierig",
        "km": "19",
        "stunden": "5,75",
        "einkehr": "Grubigalm #Hotel Schloss Fernstein#Lorea Hütte",
        "track": "A17"
    },
    {
        "nr": "18",
        "titel": "Adlerweg-Etappe 18: Lorea Hütte  Anhalter Hütte",
        "text": "Diese Route führt in eines der entlegensten Gebiete Tirols und überrascht stets aufs Neue. Almen, Steilwände und wilde Bergflanken, Almrosen und Bergblumen sind stille Begleiter, die gesunde, klare Luft der Antrieb für diese Adlerweg-Etappe.",
        "info": "Bei der Lorea Hütte hält man sich an die Beschilderung Loreakopf und wandert auf dem Steig über Almböden sanft hinauf. An der folgenden Steiggabelung links (Loreakopf), vielfach durch Schutt und oben steil empor zur Loreascharte. Auf der anderen Seite auf dem Steig durch eine Grasflanke rasant hinunter ins Heimbachtal. Im Talboden linker Hand Richtung Nassereith halten. Jetzt führt ein schmaler Steig neben dem Bach (in einer Passage direkt im Bachbett) leicht absteigend talauswärts. An der Stelle, wo das Tal einen deutlich sichtbaren Rechtsbogen einlegt, wird auf die orografisch rechte Bachseite gewechselt (Markierung am Felsen rechts nicht übersehen!). Fortan leitet das Steiglein in den Wald und in südwestlicher Richtung hinunter ins Tegestal zur Forststraße (Einmündung bei rund 1.400 Meter). Nun gemütlich ansteigend taleinwärts weiter, vorbei an der Abzweigung zur Heiterwandhütte (links)  immer in dem hier sanften Tegestal bleiben. Hinein ins Almgebiet und gemütlich nach oben zum Schweinsteinjoch (1.564 Meter, hier zweigt Route nach Sinnesbrunn ab). Vom Joch in gleichbleibender Richtung sanft durch das Almgebiet hinunter zur Hinteren Tarrentonalm (1.519 Meter). Bei der Alm der Beschilderung Anhalter Hütte folgen und auf einem breiten Forstweg gemütlich bergwärts. An der Weggabelung wenig später links halten und dem Bach entlang wandern. Die Route leitet vorbei an der Schaferhütte und verwandelt sich in einen Steig. Nun im freien Gelände unterhalb der Heiterwand dem Steig bzw. den Steigspuren folgen, meist gemächlich ansteigend zum Hinterbergjoch (2.202 Meter). Vom Hinterbergjoch über einen steilen Grashang hinunter (Schwarze Erde) und das Kar querend fast eben hinüber zum Kromsattel (Steigspuren). Vom Kromsattel leicht absteigend durch Wiesen und Almgebiet zur Anhalter Hütte.",
        "start": "Lorea Hütte",
        "ziel": "Anhalter Hütte",
        "auf": "1200",
        "ab": "1180",
        "hp": "2315",
        "grad": "mittelschwierig",
        "km": "16",
        "stunden": "6,5",
        "einkehr": "Hotel Schloss Fernstein#Lorea Hütte#Hintere Tarrentonalm#Anhalter Hütte",
        "track": "A18"
    },
    {
        "nr": "19",
        "titel": "Adlerweg-Etappe 19: Anhalter Hütte  Hanauer Hütte",
        "text": "Eine intakte Berglandschaft, Wasserfälle und plätschernde Bäche sind die Begleiter auf dieser Adlerweg-Etappe. Interessante Einblicke und Ausblicke bieten sich vom Angerletal, der Weiler Pfafflar überrascht mit seinen gestreift wirkenden Holzhäusern.",
        "info": "Von der Anhalter Hütte zunächst ein paar Meter in westlicher Richtung hinunter und dann auf dem Steig gemächlich ansteigend empor zum Steinjöchl (Seilsicherungen). Jenseits der Einsattelung vorerst direkt hinab, dann jedoch gleich sanft absteigend durch Wiesen und Latschen die Hänge querend in südwestlicher Richtung zum Hahntennjoch mit seiner alpinen Szenerie. An der Stelle, wo die Route zur Straße hinauf leitet, über Almwiesen den roten Markierungspfeilen folgend, rechter Hand auf einem Steig nach Westen hinunter  wenig später folgt Beschilderung Hanauer Hütte. Die Strecke verläuft nördlich der Straße entlang eines Steigs bzw. weiter unten auf einem Karrenweg durch Almwiesen, Latschen und lichten Mischwald gemütlich hinab. Sie führt in dem Bereich auch ein kurzes Stück durch eine kleine Schlucht. Die Route kommt in Folge zu einer Linkskehre der Straße. Ab hier wandert man auf dem Grünstreifen nördlich der Straße abwärts (Weg Nr. 601 an der Wand angeschrieben). Man gelangt bald zu den Häusern von Pfafflar (hier bestünde Abzweigemöglichkeit ins Fundaistal zum Galtseitejoch für den alternativen Zustieg zur Hanauer Hütte). Für den Normalweg jedoch an der Straße durch Pfafflar hindurch und beim Schild Nach Boden linker Hand über die Straße und den Bach. In Folge auf einem idyllischen Steig entlang des Bachs hinunter (bei Häusergruppe erneut Abzweigemöglichkeit zum Galtseitejoch für den alternativen Zustieg). Für den Normalweg aber wechselweise auf dem Steig bzw. Karrenweg in westlicher Richtung  mitunter recht steil  abwärts in die Ortschaft Boden zum Parkplatz für die Hanauer Hütte. Hier gleich den Fundaisbach überqueren und der Beschilderung Hanauer Hütte folgen. Die Route verläuft jetzt auf einem guten Forstweg und zieht nach der Überquerung des Angerlebachs in das Angerletal. Ab der Brücke steigt die Strecke wieder gemütlich an und führt jetzt durch lichten Wald. Bald zeigt sich bereits die Hanauer Hütte auf dem Plateau über dem Tal. Es folgt eine kurze absteigende Passage, ehe der Weg erneut  neben dem breiten Schotterbachbett im freien Gelände  hinauf durch das Angerletal leitet. Ab der Talstation der Materialseilbahn verwandelt sich der Fahrweg in einen Steig, der zuletzt recht steil in Serpentinen (hier auf dem Sommerweg bleiben) zur Hütte empor zieht.",
        "start": "Anhalter Hütte",
        "ziel": "Hanauer Hütte",
        "auf": "750",
        "ab": "870",
        "hp": "2188",
        "grad": "mittelschwierig",
        "km": "12,5",
        "stunden": "3,75",
        "einkehr": "Anhalter Hütte#Haunauer Hütte",
        "track": "A19"
    },
    {
        "nr": "20",
        "titel": "Adlerweg-Etappe 20: Hanauer Hütte  Württemberger Haus",
        "text": "Auf dieser Etappe von der Hanauer Hütte zum Württemberger Haus wartet neben einem herrlichen Tiefblick auf den Steinsee ein herrlicher Panoramablick auf die umliegenden Gipfel. Almen, Bergblumen, Kare, Schuttreisen und Felswände machen die Tour zu einem abwechslungsreichen Erlebnis.",
        "info": "Direkt hinter der Hanauer Hütte folgt man dem Schild Württemberger Haus. Wenig später teilt sich der Steig  wir gehen an der Stelle Richtung Steinseehütte (nicht Württemberger Haus). Knapp vor dem Bach teilt sich der Steig noch einmal  hier ist zweimal Steinseehütte angeschrieben. Für die Hintere/ Östliche Dremelscharte wählt man die Route Nr. 625 (links). Ab nun folgt man stets der Beschilderung Steinseehütte. Es geht bald über einen steilen Hang hinauf und in den Kessel zwischen Dremelspitze und Kleiner Schlenkerspitze. Nach der Querung von Schuttreisen zieht ein tadelloser Steig durch ein Schuttkar steil empor in Richtung Östliche Dremelscharte. Im obersten Teil muss eine schmale, seilversicherte Rinne (Schutt) durchquert werden. Auf der anderen Seite leitet der Steig durch Wiesen zunächst steil hinunter und anschließend meist sanft absteigend am Steinsee vorbei zur Steinseehütte. Ab der Hütte abermals ein kurzes Stück abwärts, dann gemütlich ansteigend zur Steinkarscharte. Dahinter werden Grashänge bzw. Schuttreisen gequert, ehe der Steig stärker ansteigend durch Felsen und anschließend durch Schotter zur Roßkarscharte führt. Nach der Scharte in einer engen Felsrinne (Seile) steil hinunter, später in dem etwas breiter werdenden Kar auf Schutt hinab in ein Becken. Anschließend quert der Steig Wiesenhänge und Schuttreisen und steigt dabei mäßig an. Schließlich zieht die Route steil empor zum Gebäudjoch. Jenseits auf schwarzer Erde auf einem schlechten, nicht versicherten Steig steil abwärts und hinüber zu Grashängen, die gequert werden. Schließlich in Serpentinen hinunter zum Württemberger Haus.",
        "start": "Haunauer Hütte",
        "ziel": "Württemberger Haus",
        "auf": "1240",
        "ab": "930",
        "hp": "2480",
        "grad": "schwierig",
        "km": "11",
        "stunden": "7",
        "einkehr": "Hanauer Hütte#Steinsee Hütte#Württemberger Haus",
        "track": "A20"
    },
    {
        "nr": "21",
        "titel": "Adlerweg-Etappe 21: Württemberger Haus  Memminger Hütte",
        "text": "Steinböcke gelten, so wie das Edelweiß, als ein Symbol der Alpen. Entlang dieser Adlerweg-Etappe zur Memminger Hütte ergeben sich immer wieder Möglichkeiten, Steinböcke in freier Natur zu beobachten.",
        "info": "Von der Hütte auf einem Steig zunächstein kurzes Stück hinunter. Dann werden sanft ansteigend Wiesenhänge und einSchuttkar gequert, ehe der Steig mitunter steil durch eine felsdurchsetzte Grasflanke (eine seilversicherte Stelle) zum Grat leitet. Nun links und rechts des Grats fast eben nach Norden zum Gipfel der Großbergspitze (Holzkreuz). Von der Großbergspitze führt die Route am Gratrücken ein kleines Stück sanft hinab. Ein Felsriegel wird  ansteigend  mit Hilfe von Drahtseilen überwunden, anschließend mit wenigen Schritten nach oben zum Großbergkopf. Jetzt geht es links vom Grat auf dem schottrigen Steig recht abschüssig und ausgesetzt wieder hinunter und vorbei am Großbergjoch. Danach werden  zunächst weiter absteigend  Wiesenhänge gequert, bis der Steig erneut hinaufzieht. Er quert ein Schuttkar und führt zum Schluss steiler empor zur Seescharte. Von dort auf der anderen Seite durch Schutt, Geröll und auf erdigem Boden hinab. Der Steig leitet oberhalb einer kleinen Schlucht entlang und führt ins Wiesengelände. Schließlich vorbei am größten See im Bereich der Hütte ans Etappenziel.",
        "start": "Württemberger Haus",
        "ziel": "Memminger Hütte",
        "auf": "670",
        "ab": "650",
        "hp": "2623",
        "grad": "schwierig",
        "km": "7",
        "stunden": "5",
        "einkehr": "Württemberger Haus#Memminger Hütte",
        "track": "A21"
    },
    {
        "nr": "22",
        "titel": "Adlerweg-Etappe 22: Memminger Hütte  Ansbacher Hütte",
        "text": "Diese Etappe am Adlerweg führt durch den unberührtesten Teil der Lechtaler Alpen. Sie hält neben Stille und Einsamkeit auch herrliche Aussichtspunkte und Naturerlebnisse bereit: weidende Schafe, Zirben- und Lärchenwälder und saftig grüne Almen erfreuen das Auge, gemütliche Hütten sorgen für zünftige Verpflegung.",
        "info": "Von der Memminger Hütte auf einem schmalen, lehmigen und bei Nässe rutschigen Steig zunächst direkt und bald recht jäh über Wiesenhänge hinab in Richtung Parseiertal. In der Folge quert der Steig (Wiesen)hänge (mehrmals durch Tobel) und zieht dann wieder südwestlich hinunter ins Parseiertal (Drahtseile im unteren Bereich). Dieser erste Abschnitt verläuft meist in abschüssigem Gelände. Auf der anderen Seite auf tadellosem Steig vorerst mäßig steil durch lichten Wald, später schärfer durch Wiesengelände empor. Man gelangt in der Folge ins Langkar, an dessen rechter Seite (im Spätsommer neben dem Schneefeld) der sehr gute Steig (kaum Geröll) mäßig ansteigend verläuft. Später wird die Route steiler und zieht nach links hinüber. Schließlich durch eine Art Kamin (seilversichert) recht steil und teilweise auf schwarzer Erde (Achtung bei Nässe!) nach oben zur Grießlscharte. Anschließend mit leichtem Höhenverlust und kurzem Gegenanstiegrecht steil und teilweise auf hinüber zum Winterjoch (kurz unterhalb des Winterjochs zweigt der Augsburger Höhenweg ab). Vom Winterjoch ein kleines Stück, über Schutt abwärts, hinter dem Stierkopf vorbei und jetzt felsiger empor zur Kopfscharte. Von der Kopfscharte quert der Steig die Grashänge und zieht schließlich  etwas an- und absteigend  nach Süden zur Ansbacher Hütte.",
        "start": "Memminger Hütte",
        "ziel": "Ansbacher Hütte",
        "auf": "1040",
        "ab": "900",
        "hp": "2625",
        "grad": "schwierig",
        "km": "10",
        "stunden": "6",
        "einkehr": "Memminger Hütte#Ansbacher Hütte",
        "track": "A22"
    },
    {
        "nr": "23",
        "titel": "Adlerweg-Etappe 23: Ansbacher Hütte  Kaiserjochhaus",
        "text": "Diese anspruchsvolle Adlerweg-Etappe, die mit einem herrlichen Panoramablick auf die Ötztaler Alpen belohnt, führt hoch über dem Stanzertal durch Schuttreisen, Kare und Schrofen. Etappenziel ist die Ansbacher Hütte.",
        "info": "Von der Ansbacher Hütte sanft ansteigend auf einem guten Steig hinauf zum Flarschjoch(kurz unterhalb des Jochs Abzweigemöglichkeit zur Memminger Hütte). Vom Flarschjoch führt der Steig durch Schutt und Wiesen sanft hinunter Richtung Knappenböden und dann durch Schuttreisen fast eben hinüber zum Alperschonjoch mit dem kleinen Kreuz. Nun fällt der Steig zunächst ein wenig ab, ehe er (in Serpentinen) wieder nach oben führt und schließlich zum Vordersee hinunter leitet. Diese Passage durch die Südabbrüche der Vorderseespitze heißt Haas-Weg. Der Haas-Weg quert meist Wiesen, sowie abschüssige, schrofige Felsflanken und Rinnen (vielfach versichert). Ab dem Vordersee geht es vorerst mäßig steil in Richtung Hinterseejoch. Zum Joch hin nimmt der Steig deutlich an Steilheit zu und zieht in Serpentinen auf erdigem Grund zu der Einsattelung. Jenseits des Hinterseejochs geht es  abermals in Serpentinen  mäßig steil hinab. Der Steig quert dann leicht abfallend die Schuttreisen hinüber Richtung Westen und steigt ein Stück unter der Kridlonscharte erneut an (in diesem Bereich erdiger, mitunter rutschiger Untergrund). Schließlich etwas ausgesetzt im Fels mit Hilfe von Drahtseilen durch einen Kamin empor zur Kridlonscharte. Auf der anderen Seite durch Bergwiesen hinunter und an einer Felsnase vorbei. Der Steig leitet nach Westen und quert die Hänge zum Kaiserjochhaus. Dabei führt die stellenweise sehr schmale Route durch steiles, abschüssiges und felsiges Gelände (zahlreiche versicherte Passagen) und stets ein wenig auf und ab. Die letzten Meter durch Wiesen ans Ziel.",
        "start": "Ansbacher Hütte",
        "ziel": "Kaiserjochhaus",
        "auf": "520",
        "ab": "580",
        "hp": "2481",
        "grad": "schwierig",
        "km": "8,5",
        "stunden": "5",
        "einkehr": "Ansbacher Hütte#Kaiserjochhaus",
        "track": "A23"
    },
    {
        "nr": "24",
        "titel": "Adlerweg-Etappe 24: Kaiserjochhaus  St. Christoph am Arlberg",
        "text": "Diese letzte Etappe am Nordtiroler Adlerweg führt vom Kaiserjochhaus nach St. Christoph am Arlberg. Die Route führt durch Almwiesen und Berghänge, speziell zwischen Kaiserjochhaus und Leutkircher Hütte sollte man Innehalten und dem Pfeifen der Murmeltiere lauschen. ",
        "info": "Vom Kaiserjochhaus auf dem Steig in Richtung Westen auf eine grünbewachsene Bergkuppe steigen, Seilsicherungen helfen dabei. Weiter geht es in einen Kessel mit schönen Bergwiesen. Der Steig quert die Wiesenhänge und zieht auf den Sattel zwischen Schindlekopf und Bergleskopf hinauf. Vom Sattel hinunter in einen weiteren grünen Kessel und durch die Geißwasen (Wiesengelände) quer hinüber nach Westen wandern. Am Ende der Geißwasen über eine Kuppe und weiter hinunter zur Leutkircher Hütte. Diese liegt auf 2.251 Meter am östlichen Rand des weitläufigen, schrofigen Almajurjochs. Der Steig ist bis hierher zumeist sehr lehmig, nun wird er fester. Von der Leutkircher Hütte westwärts vorbei am Almajurjoch zum Bacheregg. Hier gibt es eine Abzweigung Oberer und Unterer Höhenweg. Der Adlerweg folgt vorerst dem leichteren Unteren Höhenweg (links) durch steiles, felsdurchsetztes Gelände zum Kapallkopf (teils seilversichert). Nach langen, strengen Wintern und kaltem Frühjahr hält sich der Schnee hier lange in einer Rinne. Nun geht es ca. 50 Höhenmeter in Serpentinen hinauf zum Oberen Höhenweg und weiter Richtung Westen durch das Matun (Kessel) hinauf zum Matunjoch. Weiter zum Valfagehrjoch, dann vorbei an den Gipslöchern (Dolinen) hinunter zur Ulmer Hütte. Der Blick in Richtung Westen zur Schweizer Grenze offeriert hier grandios die Berge des Rätikon: Zimba, Schesaplana, Drusenfluh, Sulzfluh  Nach einer Rast bei der Ulmer Hütte biegt man links ab, hinunter Richtung Galzig, und wandert über grüne Bergwiesen durch das Arlberg-Skigebiet zum Speicherteich, quert oberhalb der Talstation Schindlergratbahn und wechselt dann auf den Panoramaweg, der westlich vorbei am Senderturm Galzig bis zur Bergstation führt.  Anschließend auf dem Maienweg durch Latschenfelder zum Maiensee, an diesem rechts vorbei, die Transportstraße rechts von der Brücke queren und dem kleinen Fußweg zur St. Christoph Alm folgen. Von hier führt die Almstraße bis zur Arlbergpass-Straße, wo einen die letzten Schritte dieser schönen Schluss-Etappe des Adlerweges zum Arlberg Hospiz Hotel in St. Christoph bringen.",
        "start": "Kaiserjochhaus",
        "ziel": "St. Christoph am Arlberg",
        "auf": "950",
        "ab": "1450",
        "hp": "2553",
        "grad": "mittelschwierig",
        "km": "17,5",
        "stunden": "3",
        "einkehr": "Kaiserjochhaus#Leutkircher Hütte#Ulmer Hütte",
        "track": "A24"
    },
    {
        "nr": "O1",
        "titel": "Adlerweg-Etappe O1: Ströden  Johannishütte",
        "text": "Die erste Etappe am Adlerweg in Osttirol führt von Ströden in der Nähe der berühmten Umbalfälle bis zur Johannishütte, der ältesten Hütte in den Ostalpen. Die Route führt hinauf zu gleißenden Gletschern und vorbei an tosenden Wasserfällen und sprudelnden Gletscherbächen.",
        "info": "Ausgangspunkt ist der Parkplatz in Ströden, von dort geht es nach der Brücke dem Maurerbach entlang hinauf zur Jausenstation Stoanalm auf 1.450 Meter. Auf der orografisch linken Bachseite führt der Fahrweg zur Talstation der Materialseilbahn. Weiter auf einem Steig eine lärchenbewachsene Talstufe empor. Nach ca. zwei Dutzend Steigkehren gelangt man hinauf zur Göriacher Ochsnerhütte (1.948 Meter). Weiter führt der Steig, noch immer in Bachnähe, über drei sanfte Steigungen ins Vorfeld der gletscherbedeckten Venedigerberge und zur Brücke bei der oberen Ochsnerhütte am Maurerbach. Der kraftvolle Gletscherbach trennt die Göriacher von der westlich gelegenen Maurer Alpe. Nun geht es bereits in den Schlusshang hinauf zur Essener-Rostocker Hütte, im Moränengebiet des inzwischen weit zurückgezogenen Simonykees´. Nach einer verdienten Pause wandert man von der Essener-Rostocker Hütte über den Schweriner Weg weiter. In Kehren überwindet er eine Bergflanke und quert nach ca. einer Stunde Gehzeit den Südwest-Hang des Kleinen Geigers. Nun geht es über eiszeitliche Schleifspuren und weit gestreute Schuttfelder Richtung Türml mit seinem hellen roten Fels. An seinem Fuß liegt das Türmljoch (2.772 Meter). Östlich davon führt der in Schleifen angelegte Steig durch Schneemulden und über Schuttböden und in weiterer Folge den Dorferkamm-Osthang hinab. Ca. ¼ Stunde später schwenkt man, einige Rinnsale übersteigend, nach Nordosten. Dann bewältigt der Steig noch eine dem Gelände angepasste Wende in Richtung Süden über einen Berghang, der zum Dorfer Bach hinunterführt, wo man schöne Felsschliffe bewundern kann. Schließlich geht es am Gedenkkreuz vorbei und über den Zettalunitzbach das letzte Stück zur urigen und geräumigen Johannishütte (2.121 Meter). Wegbeschreibungen siehe auch: Osttiroler Wanderbuch von Walter Mair.",
        "start": "Ströden",
        "ziel": "Johannishütte",
        "auf": "1430",
        "ab": "730",
        "hp": "2773",
        "grad": "mittelschwierig",
        "km": "13",
        "stunden": "6,5",
        "einkehr": "Stoanalm#Essener- und Rostocker Hütte#Johannishütte",
        "track": "O1"
    },
    {
        "nr": "O2",
        "titel": "Adlerweg-Etappe O2: Johannishütte  Eisseehütte",
        "text": "Entlang dieser Adlerweg-Etappe begeistern tolle Ausblick auf die benachtbarten Gletscherberge. Die Route führt von der Johannishütte über den Sajat-Höhenweg und vorbei an der Sajathütte zur Eisseehütte. ",
        "info": "Von der Johannishütte führt der Venediger Höhenweg bzw. Adlerweg Richtung Osten und erreicht bald auf einem Kehrensteig die scharf hervortretende Zopetkante. Danach geht es weiter durch steiles Bergwiesengelände, wobei man vereinzelt Steinmännchen zu Gesicht bekommt. Ab und zu lohnt sich ein Innehalten, um einen Blick auf die gleißenden Gletscher des Großvenedigers zurückzuwerfen. Nach ca. einer Stunde öffnet sich ein kleines Hochtal, man hält sich dort beim Wegweiser südlich Richtung Sajatscharte. Nach der Querung eines Blockfeldes gelangt man in hochalpines Gelände mit Steiganlage. Relativ breit und sicher, teilweise mit Stahlseilen versehen, quert der Weg die Steilflanke und führt zur Schernersschlucht, ehe er über einige Kehren im felsigen Gelände die Sajatscharte erreicht. Von hier dauert der Abstieg zur Sajathütte ca. ½ Stunde. Dabei geht es zuerst eine Schuttrinne hinunter, dann weiter auf sandigem Boden am Fuß der Roten Säule, bevor man über einen Rasenhang zur Sajathütte (2.575 Meter) gelangt. Eine willkommene Zwischenstation zur kulinarischen Stärkung, bevor man auf dem Prägratner-Höhenweg in Richtung Eisseehütte weitermarschiert. Dieser Steig verbindet die Sajathütte mit der Eisseehütte, ohne dass man dazu ins Tal absteigen muss. Man verlässt die Sajathütte in Richtung Osten und umschreitet beim sogenannten Fenster den Vorderen Sajatkopf auf dessen auslaufendem Südostgrat. Dort wendet sich der Steig Richtung Norden. Die zu querenden Steilrinnen sind wieder mit einer Steiganlage gut begehbar gemacht. Auch ein Hanganstieg ist durch bequeme Kehren entschärft. Weiter geht es durchs innere Timmeltal  bis zur Ortsbezeichnung Hinteres Wiesach, wo sich das Gelände wieder gemäßigter zeigt. Nun noch das letzte Stück über den Timmelbach zur gemütlichen Eisseehütte (2.521 Meter). Wegbeschreibungen siehe auch: Osttiroler Wanderbuch von Walter Mair.",
        "start": "Johannishütte",
        "ziel": "Eisseehütte",
        "auf": "1020",
        "ab": "620",
        "hp": "2788",
        "grad": "mittelschwierig",
        "km": "10",
        "stunden": "6",
        "einkehr": "Neue Sajathütte#Eisseehütte",
        "track": "O2"
    },
    {
        "nr": "O3",
        "titel": "Adlerweg-Etappe O3: Eisseehütte   Bonn-Matreier-Hütte",
        "text": "Gipfelerlebnisse noch und noch, selbst wenn man die Gipfel nicht erklimmt, sondern auf dem Venediger Höhenweg daran vorbeiwandert warten auf dieser Etappe von der Eisseehütte bis zur Bonn-Matreier-Hütte.",
        "info": "Von der Eisseehütte steigt man ein kurzes Stück zu den Wegtafeln des Venediger Höhenwegs hinab, wo dieser in den linken östlichen Hangbereich des Timmeltals lenkt. Die Überschreitung des auslaufenden Südwestkammes vom Hexenkopf ist leicht zu bewältigen, gleich darauf überwindet man den westlich auslaufenden Felsgrat des Hohen Eicham. Der bisher leicht und nahezu eben verlaufende Steig wird nun schärfer, denn er stößt auf den Westausläufer der Wunwand, mit der man eine Zeitlang auf Tuchfühlung bleibt. Steinerne Treppen dienen der Sicherheit, auch ein Stahlseil ist auf einem kurzen Wegstück gespannt. Es geht noch einige Kehren hinauf, man quert eine Wiesenflanke, etwa einen Kilometer bis zum Wunwand-Südwestgrat. In diesem Bereich gibt es eine Abzweigmöglichkeit zur Wallhornalm im Timmeltal, der Höhenweg führt aber weiter über eine Wiesenflanke südlich der Wunwand bis zum ausklingenden Südgrat der Wunspitze. Dort steigt man ca. ½ Stunde zu einer Felsnische hinauf. Ein Stück höher teilt sich der Steig und man könnte nach links zur Oberen und rechts zur Unteren Wunalm gelangen. Die Route des Venediger Höhenwegs verläuft nun hoch über dem Virgental, zum Teil unter den Bruchstücken eines alten Felssturzes hindurch und führt schließlich auf den Eselsrücken, der den Zugang zum Großen Niltal öffnet. 15 enge Kehren führen von der Anhöhe durch eine schmale Rasenrinne hinab auf den Sandboden. Dort ein paar Schritte über den schmächtigen Abfluss aus dem Nilkees. Das Etappenziel, die Bonn-Matreier-Hütte, ist dabei längst schon in Sicht. Auf einem guten Steig und über in den Fels gehauene Steinstufen gelangt man in den Bereich des stattlichen, schindelverkleideten Schutzhauses, das beste Verpflegung offeriert. Wegbeschreibungen siehe auch: Osttiroler Wanderbuch von Walter Mair.",
        "start": "Eisseehütte",
        "ziel": "Bonn-Matreier-Hütte",
        "auf": "600",
        "ab": "370",
        "hp": "2750",
        "grad": "mittelschwierig",
        "km": "7",
        "stunden": "3,5",
        "einkehr": "Bonn-Matreier-Hütte",
        "track": "O3"
    },
    {
        "nr": "O4",
        "titel": "Adlerweg-Etappe O4: Bonn-Matreier Hütte    Badener Hütte",
        "text": "Auf dieser schwierigen, vierten Adlerweg-Etappe in Osttirol geht es von der Bonn-Matreier-Hütte bis zur Badener Hütte. Dabei passiert man die Schärfere Galtenscharte und arbeitet sich Schritt für Schritt immer weiter zum Hoheitsgebiet des Großglockners vor.",
        "info": "Ein Stück oberhalb der Bonn-Matreier Hütte (ca. 8-10 Minuten Gehzeit), zweigt bei Wegtafeln der Steig nach rechts ab. Man durchschreitet einen steinigen Bergtrog und erreicht schließlich die schrägen Felstürme der Kälberscharte (2.791 Meter). Auf beiden Seiten der Scharte erleichtern Treppen und Stahlseile den Übergang ins Kleine Niltal, so bezwingt man auch den Aufstieg zur höher gelegenen Galtenscharte relativ problemlos. Nun erfolgt der steile, fordernde Abstieg hinunter zum Mailfroßnitzbach, obwohl man die 600 Höhenmeter später wieder wett machen muss. Der obere Teil des Steilstückes ist stahlseilversichert, im Mittelstück erwartet einen oft auch im Sommer ein hartnäckiges, steiles Schneefeld. Wenn man Glück hat und der Wegabschnitt schneefrei ist, verläuft der Steig durchgehend. Weiter unten wird das Gelände flacher, der Abstieg endet bei der Brücke über den Mailfroßnitzbach. Etwa 40 Meter unterhalb der Brücke befindet sich die Fortsetzung des Steiges. Hoch über dem Froßnitztal quert man nun die grünen Hänge der Hohen Achsel von Süden nach Norden und passiert dabei landschaftlich sehr abwechslungsreiche Teilstücke. Kurze Stellen sind stahlseilversichert, man kommt an zahlreichen kleinen Bächen vorbei. Auf der sogenannten Achsel befindet sich ein grasumwachsener, von einer Moräne abgedichteter Tümpel. Hier verbindet sich der Venediger Höhenweg mit dem Talweg. Es geht weiter in Richtung Badener Hütte, wobei man eng hintereinander gereihte Moränen und schließlich die Brücke am Froßnitzbach überschreitet. Es folgen einige Rücken und Mulden, die den Schneehühnern Schutz bieten. Schließlich gelangt man zur Seitenmoräne des Frosnitzkees´, dort hält man sich rechts und wandert weiter, bis man das Etappenziel, die Badener Hütte (2.608 Meter) am Großvenediger, erreicht. Wegbeschreibungen siehe auch Osttiroler Wanderbuch von Walter Mair.",
        "start": "Bonn-Matreier-Hütte",
        "ziel": "Badener Hütte",
        "auf": "800",
        "ab": "950",
        "hp": "2872",
        "grad": "schwarz",
        "km": "10",
        "stunden": "5",
        "einkehr": "Badener Hütte",
        "track": "O4"
    },
    {
        "nr": "O5",
        "titel": "Adlerweg-Etappe O5: Badener Hütte    Matreier Tauernhaus",
        "text": "Ein wunderbares Gletscherpanorama wartet entlang dieser Adlerweg-Etappe in Osttirol. Über den Venediger Höhenweg führt die Route nach Osten zum Venedigerhaus von Innergschlöss und schließlich weiter bis zum Etappenziel, dem Matreier Tauernhaus.",
        "info": "Von der Badener Hütte (2.608 Meter) wandert man zuerst über den Venediger Höhenweg bzw. Adlerweg (hier auch Badener Weg) nordwärts ca. eine Stunde hinauf zum Löbbentörl (2.770 Meter). Dabei sind einige felsdurchzogene Rinnen und kleine Schluchten seilversichert.  Über eine kurze Halde steigt man weiter zum Löbbentörl hinan, wo im Schutz eines Felsens ein Kreuz und eine Gedenktafel stehen. Von nun an geht es steil bergab. Der nordseitige Abstieg mit kurzen Seilstellen führt auf Fels-Rasen-Rücken und Altschnee hinunter zur Seitenmoräne des Schlatenkees´. Auf dieser Moräne steigt man weiter ab. Am Unteren Keesboden gibt es einen Übergang zur Alten Prager Hütte (nicht bewirtschaftet),  hier kann man auch zum faszinierenden Gletscherschaupfad Innergschlöss abzweigen. Der Venediger Höhenweg passiert den Salzbodensee (2.731 Meter), in dem sich Hoher Zaun und Schwarze Wand spiegeln. Nördlich des gletscherweißen Gschlössbaches wendet sich der Weg scharf nach Osten. Im gletschernahen, gut geführten Venedigerhaus (1.689 Meter) lässt sich eine gemütliche Rast einschieben. Entlang des Gschlössbaches geht es dann weiter talauswärts, zwischen den Almen von Inner- und Außergschlöss bietet sich ein Innehalten bei der alten Felsenkapelle an. Eine Einkehr weltlicher Art ist im Berghaus Außergschlöss (1.700 Meter) empfehlenswert. Das Tal weitet sich nun. Von Gschlöss geht es noch ca. eine Stunde sanft über nicht einmal 200 Höhenmeter bergab zum Matreier Tauernhaus (1.512 Meter), wo man nach den langen fordernden Abstiegen dieser Etappe vermutlich etwas knieweich ankommt. Hier kann man sich ausruhen, feine regionale Schmankerln genießen und komfortabel übernachten. Wegbeschreibungen siehe auch: Osttiroler Wanderbuch von Walter Mair.",
        "start": "Badener Hütte",
        "ziel": "Matreier Tauernhaus",
        "auf": "450",
        "ab": "1550",
        "hp": "2768",
        "grad": "schwarz",
        "km": "14",
        "stunden": "5,5",
        "einkehr": "Venedigerhaus#Matreier Tauernhaus",
        "track": "O5"
    },
    {
        "nr": "O6",
        "titel": "Adlerweg-Etappe O6: Matrei in Osttirol  Sudetendeutsche Hütte",
        "text": "Ausgehend vom Matreier Tauernhaus verläuft diese Etappe am Osttiroler Adlerweg bis zur Sudetendeutschen Hütte. Auf der Route gilt es ziemlich viele kraftraubende Höhenmeter zu absolvieren, die Mühen werden mit faszinierenden Ausblicken auf die Lasörlinggruppe belohnt.",
        "info": "Am besten startet man diese Etappe beim Parkplatz im Weiler Glanz, dann spart man sich zwei Stunden Anmarsch. Von Matrei in Osttirol kann man mit dem PKW (Taxidienst auf Anfrage) in 20 Minuten dorthin gelangen. All jene, die auch diesen ersten Streckenabschnitt zu Fuß bewältigen wollen, gelangen über den wenig befahrenen Fahrweg von Matrei über Hinterburg zum Parkplatz. Vom Parkplatz in Glanz kommt man in 1 ½  bis 2 Stunden zur Äußeren Steiner Alm und in weiteren 2 bis 2 ½ Stunden zur Sudetendeutschen Hütte. Der Steig führt großteils durch einen Wald mit uralten Lärchen, vorbei an der Köfler-Almhütte (Privatalm). Im Bereich der Ranzeralm quert man zweimal den Fahrweg. Etwas oberhalb der Lackner-Almhütte beginnt ein Karrenweg, der an einer Quelle vorbeiführt, ehe er von Osten nach Westen die Edelweißwiese durchzieht. Wer nicht durch den Wald wandern möchte, kann auch vom Parkplatz Glanz entlang der Forststraße bis zum Beginn der Edelweißwiese gehen. Nach einer Felskante fällt der durch ein Geländer geschützte Steig in den lichten Lärchenwald leicht ab. Über den Steinerbach gelangt man zu den Almhütten der Äußeren Steiner Alm (1.914 Meter), von der Äußeren Steiner Alm geht es in der flachen Trogtalsohle nordöstlich weiter in Richtung Talschluss. Kleine Lärchenhaine und gewaltige Grünschieferblöcke prägen diesen romantischen Wegabschnitt. Am Ende des Talschlusses führt eine Materialseilbahn zur Sudetendeutschen Hütte, hier befand sich früher eine Förderstätte des Eisenerz-Bergbaus, deshalb wird der Talwinkel als Schmelzhütte bezeichnet. Der Steig zur Sudetendeutschen Hütte führt zuerst nah am Steinerbach hinauf, dann windet er sich in Kehren über die Wiesenhänge empor, wobei man den Nussingkogel zur linken und die Bretterwandspitze zur rechten Seite hat. Schließlich wird das Gelände mit seinen von den Gletschern geformten Kuppen etwas flacher und schon befindet man sich im Nahbereich der geräumigen Sudetendeutschen Hütte (2.650 Meter) inmitten der Granatspitzgruppe. Wegbeschreibungen siehe auch: Osttiroler Wanderbuch von Walter Mair.  ",
        "start": "Matreier Tauernhaus",
        "ziel": "Sudetendeutsche Hütte",
        "auf": "1250",
        "ab": "100",
        "hp": "2656",
        "grad": "mittelschwierig",
        "km": "8",
        "stunden": "4",
        "einkehr": "Steiner Alm#Sudetendeutsche Hütte",
        "track": "O6"
    },
    {
        "nr": "O7",
        "titel": "Adlerweg-Etappe O7: Sudetendeutsche Hütte    Kalser Tauernhaus",
        "text": "Die Granatspitzgruppe im zentralen Bereich der Hohen Tauern fügt sich in das beeindruckende Bergpanorama dieser Adlerweg-Etappe, die von der Sudetendeutschen Hütte zum Kalser Tauernhaus führt. Dabei kommt man auf dem Teilabschnitt der Glockner-Runde dem Großglockner immer näher.",
        "info": "Von der Sudetendeutschen Hütte wandert man am Gedenkkreuz und am hüttennahen kleinen Bergsee vorbei über Rasenrücken und bemooste Mulden hinauf ins Abflussgebiet des Gradötzkees´, wo sich ebenfalls ein See angestaut hat und mächtige Moränen die Landschaft prägen. Schließlich erreicht man den Gradötzsattel (2.826 Meter), danach geht es hinunter, dem sogenannten Bloipalfen (2.684 Meter) entgegen. Anschließend weiter bergab über ein Wiesenstück und klammartig gelagerte Felsen. Auf ca. 2.500 Meter Höhe zweigt der Silesiaweg links ab. Er führt in wenigen Minuten Gehzeit auf die felsige Muntanitzschneid mit grandioser Aussicht, auf dem Adlerweg bleibend hält man sich jedoch rechts und erreicht schließlich den Muntanitzbach, der bei starker Wasserführung nicht so einfach - vor allem nicht trockenen Fußes - zu überwinden ist. Ein Stück oberhalb des Gebietes der Ochsenalm umschreitet man den auslagernden Rücken der Muntanitzschneid. Der Weg ist hier gut ausgebaut, im unteren Teil vollführt er einen kleinen Knick und weist eine felsige Stelle auf. In weiterer Folge geht es über Wiesenhänge hinunter und man durchstreift in nördlicher Richtung ein kleines Zirbenwäldchen. Man gelangt schließlich zu einer Hinweistafel zur Brücke am Stotzbach mit zufließendem Loamesbach. Bei der etwas tiefer stehenden Wegtafel wählt man den Abstieg, bez. 514 A, zum Kalser Tauernhaus. Auf zahlreichen engen Kehren wandert man nun am Wilhelm-Ernst-Weg zwischen Erlen, Eschen und Lärchen im Zickzack talwärts, an der Nationalpark-Aussichtskanzel vorbei, wo ein Wasserfall des Stotzbaches über eine von eiszeitlichen Gletschern geschaffene Trogschulter in die Tiefe wirbelt. Schließlich geht es über den Dorferbach zum Etappenziel, dem gemütlich eingerichteten Kalser Tauernhaus (1.755 Meter). Dieses befindet sich im hinteren Teil des Dorfertales, nur ein kleines Stück unterhalb jener Stelle, wo der Stotzbach in den Dorferbach mündet. Wegbeschreibungen siehe auch: Osttiroler Wanderbuch von Walter Mair.",
        "start": "Sudetendeutsche Hütte",
        "ziel": "Kalser Tauernhaus",
        "auf": "300",
        "ab": "1200",
        "hp": "2828",
        "grad": "mittelschwierig",
        "km": "8",
        "stunden": "4",
        "einkehr": "Kalser Tauernhaus",
        "track": "O7"
    },
    {
        "nr": "O8",
        "titel": "Adlerweg-Etappe O8: Kalser Tauernhaus - Stüdlhütte",
        "text": "Zollspitze, Säulspitze, Bretterspitze, Kristallspitze, Kreuzwandspitze: Entlang dieser Adlerweg-Etappe zur Stüdlhütte am Fuße des Großglockners grüßen zahlreiche markante Gipfel.",
        "info": "Vom Kalser Tauernhaus verläuft der Adlerweg bis zur Moaalm ständig in Richtung Süden durch das liebliche Dorfertal auf einem breiten Almweg leicht abwärts. Man passiert dabei u.a. die Kalseralmen der Rumesoi-und Schönebene. Bald nach der Jausenstation Bergeralm zweigt bei der Moaebene links der Weg Nr. 40 über einen Trittsicherheit erfordernden Steig (die Stiege), hinauf zur Moaalm (1.793 Meter), oberhalb von Kals. Weiter abwärts über die Moaalmstraße bis zur Brücke am Teischnitzbach, wo nach etwa 70 Meter bei einer Zaunlücke eine Wegtafel ins Teischnitztal weist. Dieses ist noch sehr ursprünglich und begeistert ebenfalls mit landschaftlicher Schönheit. Von dort führt ein Almweg auf der lärchenbewachsenen rechten Talseite empor. Es gibt aber auch einen abkürzenden Steig, der den Almweg mehrmals kreuzt. Er passiert beim Maurigen Trog (2.101 Meter), die schmale, 800 Meter lange Felsklamm (2.075 Meter). Am Eingang in den Hochtaltrog der Teischnitz-Ebene (Brücke) zeigt ein Wegweiser an, dass hier der zur Stüdlhütte führende Steig rechts in die steilen Berghänge abzweigt. Bald blickt man auf den rauschenden Teischnitzbach hinunter und sieht die Eistürme des Teischnitzkees aufblitzen. Es gilt noch einige steile Wiesenhänge, Rippen und Rinnen zu überwinden, ehe man sich abschließend über Schutt und Steinblöcke von Süden der Stüdlhütte nähert (2.802 Meter). Sie steht am Fuß vom Großglockner, das Berg- und Gletscherpanorama ist dementsprechend grandios. Wegbeschreibungen siehe auch: Osttiroler Wanderbuch von Walter Mair.",
        "start": "Kalser Tauernhaus",
        "ziel": "Stüdlhütte",
        "auf": "1440",
        "ab": "400",
        "hp": "2802",
        "grad": "mittelschwierig",
        "km": "14",
        "stunden": "6,5",
        "einkehr": "Bergeralm#Moaalm#Stüdlhütte",
        "track": "O8"
    },
    {
        "nr": "O9",
        "titel": "Adlerweg-Etappe O9: Stüdlhütte  Lucknerhaus",
        "text": "Die letzte Etappe am Osttiroler Adlerweg führt von der Stüdlhütte am Fuße des Großglockners zum Lucknerhaus. Hier endet der Adlerweg und die Kalser Glocknerstraße schlängelt sich von dort abwärts ins Tal.",
        "info": "Von der Stüdlhütte auf der Fanotscharte (2.802 Meter) steigt man in nördlicher Richtung fünf Minuten bergan, orientiert sich dann nach Osten am Wegweiser Pfortscharte, Salmhütte, Glorer Hütte, über den Weg AV 713 in Richtung Süden, Südosten. Dieser verläuft direkt unterhalb der Moränenfelder des Ködnitzkees´und mündet weit oberhalb der sogenannten Viehböden in den Johann-Stüdl-Weg (AV 702 B). Der zunächst gut ausgebaute Weg zieht nun hinauf durch Wiesenhänge, später wieder seilversichert nach oben. Jetzt hinein in das Schuttkar und darin weiter durch das Kar aufwärts. Bei einer Steiggabelung im Kar nicht rechts in die Felsen, sondern weiter Richtung Salmhütte durch das Kar aufwärts. Der Steig leitet in dieser Passage in kurzen Serpentinen durch Schutt und Geröll, aber mit gutem Untergrund. Steil geht es hinauf zur Pfortscharte. Auf der anderen Seite ein kurzes Stück in ähnlichem Gelände abwärts, bei der Steiggabelung Richtung Glorer Hütte orientieren. Von hier geht es am Luckner Weg Richtung Süden, auf grünen, welligen Bergmatten u.a. am Oberen Glatzsee vorbei und man erreicht nach einiger Zeit die Glorer Hütte am Berger Törl (2.651 Meter). Im breiten, von Wiesenhängen geprägten Bergtal finden sich Stirnmoränen ehemaliger Gletschertätigkeit, die bis in die Mulde mit dem Glatzbach reichen. Nach der Glorer Hütte verläuft der Weg parallel zur Materialseilbahn auf zum Teil erdigem Steig und über einige kleinere Bächlein weiter talwärts zwischen Bergwiesen hinunter, wo man sich zum Schutz der Natur auf dem Steig halten sollte. Schließlich mündet der Steig in einen breiten Weg, der zum Lucknerhaus führt. Etappenziel und Ende des Adlerweges Osttirol! Oder der schöne Beginn, wenn man ihn von dieser Seite aus in Angriff nimmt. Wegbeschreibungen siehe auch: Osttiroler Wanderbuch von Walter Mair.",
        "start": "Stüdlhütte",
        "ziel": "Lucknerhaus",
        "auf": "450",
        "ab": "1330",
        "hp": "2824",
        "grad": "mittelschwierig",
        "km": "11",
        "stunden": "5,5",
        "einkehr": "Glorer Hütte#Luchknerhaus",
        "track": "O9"
    }
];